### ISSUE TITLE
Add support for Spark 2.2

### ISSUE THREAD

**Issue by markderry** [bkvarda/kudusparklyr#4] opened 2017-09-19 20:52 UTC
We would like to add support for spark 2.2 and I believe that we would need to update the .jar file.

**Comment by bkvarda** [comment] 2017-09-21 22:49
Just saw this - I think I should be able to take care of it tonight.

**Comment by markderry** [comment] 2017-09-21 22:50
Awesome! We just upgraded and I have had to revert to spark 1.6 to get things to run and we have been having all kinds of troubles!

**Comment by bkvarda** [comment] 2017-09-21 22:52
Okay got it - did you just upgrade Spark or CDH/Kudu also?

**Comment by markderry** [comment] 2017-09-21 22:54
We just upgraded to kudu 1.4.0-cdh5.12.1

**Comment by bkvarda** [comment] 2017-09-22 05:00
Pushed changes. You will have to set an option before creating your spark connection to specify the kudu version (this is how it will select which JARs to use). Let me know if this works and if not, send me any errors so I can repro - I wasn't able to test extensively. 

options(kudu.version="1.4.0")
sc <- spark_connect(master="yarn-client",version="2.2", config = list(default = list(spark.yarn.keytab="/home/ec2-user/navi.keytab",spark.yarn.principal="navi@CLOUDERA.INTERNAL")))

**Comment by bkvarda** [comment] 2017-09-26 16:25
Mark - did this fix the issue(s)?

**Comment by markderry** [comment] 2017-09-26 16:43
Somewhat, it failed when I went to add the kudu context to the connection and said that I needed to set spark multiple contexts to true and I have been trying to find where I would do that.

**Comment by krb16704** [comment] 2017-09-27 21:03
I've been working with mark on this one. We have solved that issue, but we are running into another one about the create kudu table method not found. I opened another issue #5 to reference it specifically

**Comment by bkvarda** [comment] 2017-09-28 16:06
I think this and #5 may be related. I will try doing some extensive testing to figure out the cause over the next week or so.

**Comment by bkvarda** [comment] 2017-10-02 22:02
@krb16704 This should be fixed now. The issue was that in the Scala Java/Kudu library that this depends on, Spark 1.6 was deprecated, and now that code uses the existing SparkContext instead of creating a new one as shown below:
`
@InterfaceStability.Unstable
class KuduContext(val kuduMaster: String,
                  sc: SparkContext) extends Serializable {
  import kudu.KuduContext._

  @Deprecated()
  def this(kuduMaster: String) {
    this(kuduMaster, new SparkContext())
  }
`
So the error message was accurate - there were 2 contexts being created, but that should not be the case any longer. Let me know if this fixes the issue.

**Closed as completed** 2017-10-11 18:46 UTC
